### ISSUE TITLE
Prepare app for MVP preview

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#119]
# Todo:

* [x] use develop branch
* [x] update buefy toast component
* [x] evtl. add fixes from feature branches
* [x] comment out components, links, markup and routes which are not needed
  * [x] audio publications?
  * [x] transcriptions
  * [x] chapter marks
  * [x] persons?

**Comment by Letty** [comment]
- [ ] Add "Import Podcast" to network overview site
