### ISSUE TITLE
As podcaster I want all delete actions to have a confirmation modal

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#207]
# Todo

* [ ] delete network
* [ ] delete podcast
* [ ] delete episode
* [ ] delete audio publication
* [ ] delete contributor
* [ ] delete audio in audio publications
* [ ] delete audio in episode
* [ ] delete images in network
* [ ] delete images in podcast
* [ ] delete images in people
* [ ] delete images in episode
* [ ] delete images in audio publication
