### ISSUE TITLE
As podcaster I want to add wikidata articles to an episode

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#21]
# Description

We need a component that adds an input field with auto suggest of wiki data articles, to add wikidata articles to an episode. Component should emit selected wikidata articles to parent.

# Todo

* [ ] Add input field with autosuggest
* [ ] Use wikidata API for auto suggesting wikidata articles
* [ ] Emit selected articles

**Comment by Letty** [comment]
Documentation about [search API](https://www.mediawiki.org/wiki/API:Search)

Example search for `Science`: `https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=Science&utf8=&format=json`

Attributes of interest in response: `title`, `pageid` and `snippet`

**Comment by Letty** [comment]
Questions:

- [ ] How to identify the language? You want to search in the language of your (episode) content.
