### ISSUE TITLE
As podcaster I want a podcast page with an analytics and episode overview for every podcast

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#24]
# Todo

* [ ] write markup and css in style of wireframe
* [ ] at least analytics section and episode section should be components (maybe use more)
* [ ] get data in parent from store
* [ ] get data from api, use static mock data if there is no api request yet (e.g. analytics)
* [ ] test components

# Wireframes

![1024_Podcast](https://user-images.githubusercontent.com/3409561/58705231-de61a480-83ae-11e9-9135-1b1de6047260.png)
