### ISSUE TITLE
As podcaster I want to see a podcasts analytics

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#25]
# Todo

* [ ] add new page for each podcast with route `http://localhost:3000/networks/[nid]/podcasts/[pid]/episodes/[eid]/analytics`
* [ ] add route to navigation
* [ ] add downloads table and graph (wireframe is only a first try – might be sth much cooler, e.g. the graph reacting to hovering/selecting columns or rows in the table, ...)
* [ ] get data from store
* [ ] get data from api, use static mock data if there is no api request yet (e.g. analytics)
* [ ] test components

# Wireframe

@Letty Like I said, wireframe was only a first draft, UX research though has shown that the table with the customisable headlines (Overall, 4 Weeks, 2 Weeks, etc.) is really useful for the podcasters – so we should use this. In a perfect world we would then see a dynamic visualisation for hovered/selected rows or columns of the table above it. What do you think?

![1024_Analytics](https://user-images.githubusercontent.com/3409561/58705764-6c8a5a80-83b0-11e9-99fc-ae6d784db815.png)
