### ISSUE TITLE
As podcaster I want to have an episode page

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#26]
# Todo

* [x] write markup and css in style of wireframe (navigation is not correct in wireframe, pls ignore)
* [x] sections should be components (maybe use more)
* [ ] get data in parent from store
* [ ] get data from api, use static mock data if there is no api request yet (e.g. analytics)

# Wireframe

![1024_Episode](https://user-images.githubusercontent.com/3409561/58706885-84171280-83b3-11e9-94e4-fc4b79a54383.png)
