### ISSUE TITLE
As podcaster I want to create a new episode

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#27]
# Todo

* [x] write markup and css in style of wireframe
* [x] at least analytics section and episode section should be components (maybe use more)
* [x] get data from api, use static mock data if there is no api request yet (e.g. analytics)
* [ ] get and post data to store
* [ ] post data to api if possible yet
* [ ] test components and page
* [ ] add transcript creation
* [ ] add contributor creation
* [ ] add chapter marks creation

# Info

* For lists we can use the [sortable extension](https://buefy.org/extensions/sortablejs/) of Buefy.
* For validation we can use the [validation extension](https://buefy.org/extensions/veevalidate/) of Buefy.
* Speak with Eric about saving shownotes as markdown and parse it on the server to html.
* At least for Shownotes (content) we need a rich text editor. Here are two libraries that look good:
    * [tiptap](https://tiptap.scrumpy.io/): Looks small and nice – checkout if multi-edit is possible.
    * [CKEditor](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html): Bigger but I guess more reliable, customisable and maybe also relatively easy to use for editing by multiple people.
    * [Here's also a list with more Vue.js editors.](https://vuejsexamples.com/tag/editor/)

# Wireframes

![1024_Episode--new](https://user-images.githubusercontent.com/3409561/58707614-bde91880-83b5-11e9-9b8b-45f6fe1caf04.png)
