### ISSUE TITLE
As podcaster I want to see the episode I am currently viewing/editing in the navigation

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#38]
# Todo

* [x] Add another dropdown next to the podcasts dropdown for episodes.
* [x] While viewing/editing an episode, the podcaster should see the currently active episode title as the dropdown's label (as seen on the podcasts and networks dropdown).
* [x] Restrict the height of the dropdown and make it scrollable, if possible.
* [ ] Sort episodes in dropdown from latest (high in list) to oldest (at the bottom of the list).
* [x] Link the episodes to their episode page.
* [x] When the podcaster currently views a podcast page, the label of the episode dropdown should be "Episodes".
* [x] When the podcaster currently views a network page, the episodes dropdown is not visible.
* [x] Add missing pointer cursor to the navigation buttons.

**Comment by Letty** [comment]
- [ ] Bug: When navigating to an Episode, the selected Podcast is no longer in the store..
