### ISSUE TITLE
As podcaster I want to be able to invite people to my networks, podcasts, episodes and audio-publication

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#62]
# Todo

* [x] Show persons in podcast 
* [x] Show persons in episode
* [x] Show persons in audio-publication
* [x] Add, update, delete persons in podcast
* [x] Add, update, delete persons in episode
* [x] Add, update, delete persons in audio-publication

# Info

* User = Auth = Collaborator = Team-Member – NOT IN MVP
  * Person = all persons (no richts), doesn't point to user - MVP
  * Contribution = person in audio or episode - MVP

# Questions

* Which roles are there for contributions?
