### ISSUE TITLE
As podcaster I want to upload audio files to a network and not a podcast

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#64]
# Todo

* [x] UX Design
* [x] Markup, Styling
* [x] API create audio
* [x] API create audio_file
* [x] API update audio
* [x] API update audio_file
* [ ] API delete audio
* [ ] API delete audio_file
* [x] API get audio
* [x] API get audio_file

# Info

Route: `/networks/[network_id]/audios/new`
