### ISSUE TITLE
As podcaster I want to see the update/publish history of an episode

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#78]
# Todo

* [ ] Get info from backend development about the GraphQL API
* [ ] Implement on episode pages
* [ ] Implement on audio-publication pages

# Info

Maybe implement as new tab on episode page.

# Questions

* Will this feature only be used for episodes and audio-publication pages or also for podcasts and/or networks?
