### ISSUE TITLE
As podcaster I want to add a number, slug and shortid to episodes

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#94]
# Todo

* [ ] make number suggestion dynamic (last episode + one)
* [ ] make slug suggestion
* [ ] make shortid suggestion
